export const ROLES = {
    ADMIN: 'ADMIN',
    MEMBER: 'MEMBER',
    OWNER: 'OWNER'
};



export const Permissions = {
    CREATE_WORKSPACE: 'CREATE_WORKSPACE',
    DELETE_WORKSPACE: 'DELETE_WORKSPACE',
    EDIT: 'EDIT',
    MANAGE_WORKSPACE_SETTING: 'MANAGE_WORKSPACE_SETTING',

    ADD_MEMBER: 'ADD_MEMBER',
    CHANGE_MEMBER_ROLE: 'CHANGE_MEMBER_ROLE',
    REMOVE_MEMBER: 'REMOVE_MEMBER',

    CREATE_PROJECT: 'CREATE_PROJECT',
    EDIT_PROJECT: 'EDIT_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',

    CREATE_TASK: 'CREATE_TASK',
    EDIT_TASK: 'EDIT_TASK',
    DELETE_TASK: 'DELETE_TASK',

    VIEW_ONLY: 'VIEW_ONLY'
}